# docker build -f .build/Dockerfile --build-arg APPNAME=Xtkl.NceTransferWebhooks --build-arg AZURE_NUGET_PWD=$AZURE_NUGET_PWD -t ra2cr11cumulus.azurecr.io/nce-transfer:poc .
# az acr login -n ra2cr11cumulus
# docker push ra2cr11cumulus.azurecr.io/nce-transfer:poc
# kubectl apply -f .build/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nce-transfer
  namespace: poc
  labels:
    app: nce-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nce-transfer
  template:
    metadata:
      labels:
        app: nce-transfer
    spec:
      containers:
      - name: nce-transfer
        image: ra2cr11cumulus.azurecr.io/nce-transfer:poc
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nce-transfer
  name: nce-transfer
  namespace: poc
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nce-transfer
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nce-transfer
  namespace: istio-system
spec:
  hosts:
  - "nce-transfer.dev.sherweb.com"
  gateways:
  - cumulus-gateway
  http:
    - match:
        - scheme:
            exact: http
      redirect:
        scheme: https
    - route:
        - destination:
            host: nce-transfer.poc.svc.cluster.local
            port:
              number: 8080

